import StaticPage from '@/components/StaticPage';

export const metadata = { title: 'Privacy Policy — Shannonware' };

export default function PrivacyPage() {
  return (
    <StaticPage label="PRIVACY POLICY" title="Privacy Policy">
      <p>Shannon Douglas Ware (shannonware.com) does not collect any personally identifiable user information. You retain rights over any cookies generated by this site which are stored on your machine.</p>
      <p>From 26 June 2025, shannonware.com hosts banner ads from Google AdSense. All cookies and tracking are in accordance with Google privacy policy, including the right to reject cookies and tracking information.</p>
    </StaticPage>
  );
}
